#include "auto_header.h"
#include <fcntl.h>
#include <stdio.h>
#include <string.h>

static int      add_comment(FILE *f)
{
    fprintf(f, "/*\n");
    fprintf(f, "** |~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~|\n");
    fprintf(f, "** |--------------GENERATED BY AUTO_HEADER--------------|\n");
    fprintf(f, "** |                                                    |\n");
    fprintf(f, "** |   https://github.com/kagestonedragon/auto_header   |\n");
    fprintf(f, "** |~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~|\n");
    fprintf(f, "*/\n\n");
    return (0);
}

static int      add_main(FILE *f, t_auto_header *core)
{
    get_define(core);
    fprintf(f, "#ifndef %s\n", core->file_variable);
    fprintf(f, "# define %s\n", core->file_variable);
    return (0);
}

static int      add_includes(FILE *f, t_auto_header *core)
{
    t_list      *temporary;

    if (core->includes_files)
    {
        temporary = core->includes_files;
        while (temporary)
        {
            fprintf(f, "# include \"%s\"\n", temporary->data);
            temporary = temporary->next;
        }
    }
    fprintf(f, "\n");
    return (0);
}

static int      find_prototypes(FILE *f, t_dir *dir, int max_tab, char *file_name)
{
    t_list      *temporary;
    t_prot      *list;
    int         tab;
    int         i;
    
    temporary = dir->files;
    while (temporary)
    {
        i = 0;
        fprintf(f, "/*\n");
        fprintf(f, "** %s/%s\n", dir->data, temporary->data);
        fprintf(f, "*/\n");
        list = temporary->prototype;
        while (list)
        {
            fprintf(f, "%s", list->type_data);
            fprintf(f, "\t\t");
            if ((tab = max_tab - list->tab) > 0)
                while (tab--)
                    fprintf(f, "\t");
            fprintf(f, "%s;\n", list->info_data);
            list = list->next;
            i += 1;
        }
        if (i == 1) 
            printf("\e[92madd \e[91m%d \e[92mprototype ", i);
        else
            printf("\e[92madd \e[91m%d \e[92mprototypes ", i);
        printf("from \e[91m%s/%s \e[92mto \e[93m%s\e[0m\n", dir->data, temporary->data, file_name);
        fprintf(f, "\n");
        temporary = temporary->next;
    }
    return (0);
}

static int      add_prototypes(FILE *f, t_auto_header *core)
{
    t_dir       *temporary;
    int         max_tab;
 
    temporary = core->sources_folders->directories;
    max_tab = temporary->max_tab;
    while (temporary)
    {
        find_prototypes(f, temporary, max_tab, core->file_name);
        temporary = temporary->next;
    }
    return (0);
}

int             create_prototype(t_auto_header *core)
{
    FILE        *f;

    if(!(f = fopen(core->file_name, "w")))
        parsing_errors(ERROR_HEADER, core->file_name);
    add_comment(f);
    add_main(f, core);
    add_includes(f, core);
    add_prototypes(f, core);
    fprintf(f, "#endif");
    return (0);
}
